#! /usr/bin/env python3


import sys
import requests
from bs4 import BeautifulSoup as bs

translate_queue = sys.argv[1:]

def format(content):
    try:
        return f"{content['header']}\n{content['results']}"
    except:
        try:
            translate_queue.append(content['similar_word'])
            return "there is nothing for your query, did you mean:"
        except:
            return "unable to find anything"

class TranslateSession:
    __requestsSession = None

    def __init__(self):
        self.__requestsSession = requests.Session()

    def translate(self, query):
        soup = self.__upload_page(query)
        if is_russian_text(query):
            results = self.__translate_ru_to_en(soup)
        else:
            results = self.__translate_en_to_ru(soup)

        results['header'] = query

        if not 'results' in results:
            results = self.__parse_unfound_word(soup)
 
        return format(results)

    def __upload_page(self, query):
        response = requests.get(f'https://wooordhunt.ru/word/{query}') 
        soup = bs(response.content, 'html.parser')
        return soup

    def __translate_en_to_ru(self, soup):
        return TranslateSession.__init_dict(soup.find(attrs = {'class': 't_inline_en'}), 'results')

    def __translate_ru_to_en(self, soup):
        return TranslateSession.__init_dict(soup.find(attrs = {'class': 't_inline'}), 'results')
    
    def __parse_unfound_word(self, soup):
        return TranslateSession.__init_dict(soup.find(attrs = {'class': 'possible_variant'}), 'similar_word')
    
    @staticmethod
    def __init_dict(bs_obj, key):
        if bs_obj is None:
            return {}
        else:
            return {key: bs_obj.text}

def is_russian_text(text):
    ALPHABET = set('абвгдеёжзийклмнопрстуфхцчшщъыьэюя')
    return not ALPHABET.isdisjoint(text)


if __name__ == '__main__':
    try:
        session = TranslateSession()
        for arg in translate_queue:
            output = session.translate(arg)
            print(output)
    except:
        print('no connection')
